"""
test_codegen.py
---------------
Automated tests for code generation.

Run from the project root with:
    pytest -v

Two kinds of tests:
  1. "Shape" tests  - the generated Python TEXT contains the expected line.
  2. "Run" tests    - we actually EXECUTE the generated code on a small CSV
                      and check what it prints. This proves the translation
                      is correct, not just that it looks right.
"""

import matplotlib

# Use a non-interactive backend so plot tests never try to open a window.
# Must be set before pyplot is imported anywhere.
matplotlib.use("Agg")

import pytest  # noqa: E402  (import after matplotlib.use is intentional)

from codegen import compile_source, strip_dsl_comment  # noqa: E402

DATA_CSV = (
    "name,city,marks\n"
    "Aarav,Hyderabad,78\n"
    "Diya,Chennai,55\n"
    "Rohan,Bengaluru,91\n"
    "Sneha,Hyderabad,64\n"
)


@pytest.fixture
def workdir(tmp_path, monkeypatch):
    """Create data.csv in a temp folder and make that the current directory."""
    (tmp_path / "data.csv").write_text(DATA_CSV, encoding="utf-8")
    monkeypatch.chdir(tmp_path)
    return tmp_path


def generate(*lines):
    """Helper: compile a program that starts with 'load "data.csv"'."""
    source = "\n".join(['load "data.csv"', *lines])
    python_code, _ = compile_source(source, "test.dsl")
    return python_code


def run_generated(python_code, capsys):
    """Helper: execute generated code in a fresh namespace, return what it printed."""
    exec(compile(python_code, "<generated>", "exec"), {})
    return capsys.readouterr().out


# ---------------------------------------------------------------------------
# Shape tests: one per statement type
# ---------------------------------------------------------------------------

def test_header_and_import(workdir):
    code = generate("show")
    assert code.startswith("# Generated by the Data Analysis DSL Compiler from test.dsl")
    assert "import pandas as pd" in code
    assert "matplotlib" not in code  # not imported when there's no plot


def test_load(workdir):
    assert "df = pd.read_csv('data.csv')" in generate("show")


def test_filter_number_and_text(workdir):
    code = generate("filter marks >= 60", 'filter city == "Hyderabad"', "show")
    assert "df = df[df['marks'] >= 60]" in code
    assert "df = df[df['city'] == 'Hyderabad']" in code


def test_select(workdir):
    assert "df = df[['name', 'marks']]" in generate("select name, marks", "show")


def test_sort(workdir):
    assert "df = df.sort_values('marks', ascending=False)" in generate("sort marks desc", "show")
    assert "df = df.sort_values('marks', ascending=True)" in generate("sort marks", "show")


def test_print_avg_uses_mean_and_round(workdir):
    assert "print('avg(marks)', '=', round(df['marks'].mean(), 2))" in generate("print avg(marks)")


def test_source_lines_become_comments(workdir):
    code = generate("filter marks > 60", "show")
    assert "# line 2: filter marks > 60" in code


def test_generated_code_is_valid_python(workdir):
    code = generate("filter marks > 60", "select name, marks", "sort marks", "show",
                    "print count(name)", "plot bar name marks")
    compile(code, "<generated>", "exec")  # raises SyntaxError if invalid


# ---------------------------------------------------------------------------
# Run tests: execute the generated code and check the real results
# ---------------------------------------------------------------------------

def test_run_filter_sort_show(workdir, capsys):
    output = run_generated(generate("filter marks > 60", "select name, marks", "sort marks desc", "show"), capsys)
    lines = [line.split() for line in output.strip().splitlines()]
    assert lines[0] == ["name", "marks"]
    # Diya (55) is filtered out; the rest are in descending order of marks.
    assert [row[0] for row in lines[1:]] == ["Rohan", "Aarav", "Sneha"]


def test_run_text_filter(workdir, capsys):
    output = run_generated(generate('filter city == "Hyderabad"', "print count(name)"), capsys)
    assert "count(name) = 2" in output


@pytest.mark.parametrize(
    "function, expected",
    [("count", "4"), ("sum", "288"), ("avg", "72.0"), ("min", "55"), ("max", "91")],
)
def test_run_aggregates(workdir, capsys, function, expected):
    output = run_generated(generate(f"print {function}(marks)"), capsys)
    assert output.strip() == f"{function}(marks) = {expected}"


def test_run_plot_saves_png(workdir, capsys):
    output = run_generated(generate("plot bar name marks"), capsys)
    assert (workdir / "output" / "test_plot_line2.png").exists()
    assert "Chart saved to" in output


def test_string_values_cannot_inject_code(workdir, capsys):
    """A malicious-looking filter value must stay a plain string literal."""
    evil = "x'); print('HACKED'); ('"
    code = generate(f'filter city == "{evil}"', "print count(name)")
    output = run_generated(code, capsys)
    assert "HACKED" not in output
    assert "count(name) = 0" in output


@pytest.mark.parametrize(
    "line, expected",
    [
        ("show", "show"),
        ("  sort marks desc   # newest first", "sort marks desc"),
        ('filter tag == "#1"   # keep the hash', 'filter tag == "#1"'),
        ("# whole line comment", ""),
    ],
)
def test_strip_dsl_comment(line, expected):
    assert strip_dsl_comment(line) == expected
