"""
codegen.py
----------
PHASE 5 of the compiler: Code Generation.
(Phase 4, the optimizer, sits between semantic analysis and code generation;
we build it in Step 6. The pipeline works without it.)

The code generator walks the checked AST and writes an equivalent program
in the TARGET language - here, Python using the pandas library.

    DSL (source language)            Python (target language)
    ---------------------            ------------------------
    load "students.csv"         ->   df = pd.read_csv('students.csv')
    filter marks > 60           ->   df = df[df['marks'] > 60]
    select name, marks          ->   df = df[['name', 'marks']]
    sort marks desc             ->   df = df.sort_values('marks', ascending=False)
    show                        ->   print(df.to_string(index=False))
    print avg(marks)            ->   print('avg(marks) =', round(df['marks'].mean(), 2))

This is what makes the project a COMPILER rather than an interpreter:
    - an interpreter executes the program directly;
    - a compiler TRANSLATES it into another language, which runs later.
Our output is a normal .py file you can open, read, and run on its own.

THE TECHNIQUE: syntax-directed translation
    Each AST node type has one method that returns the Python lines for it
    (a "template" per node). Visiting the nodes in order and joining their
    lines gives the whole program. The working table always lives in one
    variable called `df` (DataFrame), and every step replaces it.

SECURITY NOTE
    Strings from the user (file names, filter values) are written with
    repr(), which produces a correctly escaped Python literal. So a value
    like  "x'); import os; ('"  becomes a harmless string, never code.
    Building code by gluing raw text together would allow CODE INJECTION.

Run this file directly to generate and print the Python code:
    python src/codegen.py examples/analysis.dsl
"""

import os
import sys

from ast_nodes import (
    FilterNode,
    LoadNode,
    PlotNode,
    PrintNode,
    Program,
    SelectNode,
    ShowNode,
    SortNode,
)
from errors import DSLError
from semantic import analyze_source

# DSL aggregate name -> pandas method name.
AGGREGATE_METHODS = {
    "count": "count",
    "sum": "sum",
    "avg": "mean",   # pandas calls the average 'mean'
    "min": "min",
    "max": "max",
}


class CodeGenerator:
    """Translates a checked Program (AST) into Python/pandas source code.

    Usage:
        python_code = CodeGenerator(source_code, "examples/analysis.dsl").generate(program)

    The generator assumes the program already passed semantic analysis,
    so it doesn't re-check column names or types.
    """

    def __init__(self, source_code: str = "", source_name: str = "<input>", output_dir: str = "output"):
        """Args:
            source_code: the original DSL text; each DSL line is copied into
                         the output as a comment, so you can see which DSL
                         line produced which Python lines (traceability).
            source_name: file name shown in the generated header comment.
            output_dir:  folder where charts from 'plot' are saved.
        """
        self.source_lines = source_code.splitlines()
        self.source_name = source_name
        self.output_dir = output_dir
        # Base name used for chart files, e.g. "analysis" from "analysis.dsl".
        self.base_name = os.path.splitext(os.path.basename(source_name))[0] or "program"

    # ------------------------------------------------------------------
    # Entry point
    # ------------------------------------------------------------------

    def generate(self, program: Program) -> str:
        """Return the complete Python program as one string."""
        uses_plot = any(isinstance(node, PlotNode) for node in program.statements)

        lines = [
            f"# Generated by the Data Analysis DSL Compiler from {self.source_name}",
            "# Do not edit this file by hand - change the .dsl file and recompile.",
            "",
            "import pandas as pd",
        ]
        # Only import matplotlib if it's actually needed: faster startup,
        # and the script still runs on machines without matplotlib.
        if uses_plot:
            lines.append("import os")
            lines.append("import matplotlib.pyplot as plt")
        lines.append("")

        # Dispatch table: node class -> method returning that node's Python lines.
        generators = {
            LoadNode: self._gen_load,
            FilterNode: self._gen_filter,
            SelectNode: self._gen_select,
            SortNode: self._gen_sort,
            ShowNode: self._gen_show,
            PrintNode: self._gen_print,
            PlotNode: self._gen_plot,
        }

        for node in program.statements:
            lines.append(self._source_comment(node))
            lines.extend(generators[type(node)](node))
            lines.append("")

        return "\n".join(lines).rstrip() + "\n"

    def _source_comment(self, node) -> str:
        """Return a comment like '# line 5: filter marks > 60'."""
        if 1 <= node.line <= len(self.source_lines):
            original = self.source_lines[node.line - 1].strip()
            return f"# line {node.line}: {original}"
        return f"# line {node.line}"

    # ------------------------------------------------------------------
    # One template per node type. Each returns a LIST of Python lines.
    # ------------------------------------------------------------------

    def _gen_load(self, node: LoadNode) -> list:
        """load "f.csv"  ->  read the CSV into df."""
        return [f"df = pd.read_csv({node.path!r})"]

    def _gen_filter(self, node: FilterNode) -> list:
        """filter col op value  ->  boolean indexing.

        df['marks'] > 60 gives a True/False value per row ("a mask");
        df[mask] keeps only the True rows.
        """
        return [f"df = df[df[{node.column!r}] {node.operator} {node.value!r}]"]

    def _gen_select(self, node: SelectNode) -> list:
        """select a, b  ->  keep only these columns (double brackets = list of columns)."""
        return [f"df = df[{node.columns!r}]"]

    def _gen_sort(self, node: SortNode) -> list:
        """sort col [asc|desc]  ->  sort_values."""
        return [f"df = df.sort_values({node.column!r}, ascending={node.ascending})"]

    def _gen_show(self, node: ShowNode) -> list:
        """show  ->  print the whole table.

        to_string(index=False) prints every row without pandas' row
        numbers, which look confusing after filtering (0, 2, 5...).
        """
        return [
            "print(df.to_string(index=False))",
            "print()",
        ]

    def _gen_print(self, node: PrintNode) -> list:
        """print fn(col)  ->  compute and print one value with a label."""
        method = AGGREGATE_METHODS[node.function]
        label = f"{node.function}({node.column})"
        expression = f"df[{node.column!r}].{method}()"
        if node.function == "avg":
            # Averages are usually long decimals; 2 places is easier to read.
            expression = f"round({expression}, 2)"
        return [f"print({label!r}, '=', {expression})"]

    def _gen_plot(self, node: PlotNode) -> list:
        """plot kind x y  ->  draw a chart, save it as PNG, then show it.

        Saving to a file means you always have the chart, even on a machine
        without a screen; plt.show() opens a window when one is available.
        os.makedirs(..., exist_ok=True) creates the folder if it's missing
        and does nothing if it already exists.
        """
        image_path = f"{self.output_dir}/{self.base_name}_plot_line{node.line}.png"
        title = f"{node.y_column} by {node.x_column}"
        return [
            f"os.makedirs({self.output_dir!r}, exist_ok=True)",
            f"df.plot(kind={node.kind!r}, x={node.x_column!r}, y={node.y_column!r}, title={title!r})",
            "plt.tight_layout()",
            f"plt.savefig({image_path!r})",
            f"print('Chart saved to', {image_path!r})",
            "plt.show()",
        ]


def compile_source(source_code: str, source_name: str = "<input>", output_dir: str = "output"):
    """Run Phases 1-3 and code generation on raw text.

    Returns:
        (python_code, warnings)
    Raises:
        LexerError, ParseError or SemanticError (all DSLError subclasses).
    """
    program, warnings = analyze_source(source_code)
    python_code = CodeGenerator(source_code, source_name, output_dir).generate(program)
    return python_code, warnings


def main():
    """Command-line entry point: python src/codegen.py <file.dsl>

    Writes output/<name>.py and prints the generated code.
    (Step 5's main.py will also RUN it for you.)
    """
    if len(sys.argv) != 2:
        print("Usage: python src/codegen.py <file.dsl>")
        sys.exit(1)

    file_path = sys.argv[1]
    try:
        with open(file_path, encoding="utf-8") as file:
            source_code = file.read()
    except FileNotFoundError:
        print(f"Error: file not found: {file_path}")
        sys.exit(1)

    try:
        python_code, warnings = compile_source(source_code, file_path)
    except DSLError as error:
        print(error.format(source_code))
        sys.exit(1)

    for warning in warnings:
        print(f"Warning: {warning}\n")

    os.makedirs("output", exist_ok=True)
    base_name = os.path.splitext(os.path.basename(file_path))[0]
    output_path = os.path.join("output", base_name + ".py")
    with open(output_path, "w", encoding="utf-8") as file:
        file.write(python_code)

    print(python_code)
    print(f"Generated: {output_path}")
    print(f"Run it with: python {output_path}")


if __name__ == "__main__":
    main()
